install:
    - curl https://raw.githubusercontent.com/back4app/parse-cli/back4app/installer.sh | sudo /bin/bash
    - sudo apt-get -y update
    - sudo apt-get install -y expect
  
deploy:
    provider: script
    script: deploy/expect.exp
    on:
        branch: develop
      